# Generated by Django 4.2 on 2024-03-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deepfake", "0002_video_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="pred_class",
            field=models.CharField(default="Default", max_length=100),
        ),
    ]
